version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      
  post_build:
    commands:
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment_package.zip s3://lambdagithubdoordash-zip/
      - echo "Deployment package uploaded to S3."
      
      - echo "Extracting JSON file from deployment package..."
      - unzip -o deployment_package.zip 2024-03-09-raw_input.json -d .
      - echo "JSON file extracted."
      
      - echo "Uploading JSON file to S3 bucket 'doordash-landing-zn'..."
      - aws s3 cp 2024-03-09-raw_input.json s3://doordash-landing-zn/
      - echo "JSON file uploaded to S3 bucket 'doordash-landing-zn'."
